# Generated by Django 2.2.12 on 2022-11-03 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LOGIN', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='desc',
            new_name='Taskdesc',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='title',
            new_name='Tasktitle',
        ),
    ]
